[package]
name = "poseidon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
halo2wrong = { workspace = true }
maingate = { workspace = true }
ff = { workspace = true }
rand_core = { workspace = true }